services:
  spark-master:
    image: spark
    build: .
    container_name: spark-master
    entrypoint: "/bin/sh"
    command: -c "/opt/spark/sbin/start-master.sh; tail -f /dev/null"
    ports:
      - '8080:8080'
      - '4040:4040'
    volumes:
      - .:/app
      - spark-events:/opt/spark/events

  spark-worker:
    image: spark
    build: .
    container_name: spark-worker1
    entrypoint: "/bin/sh"
    command: -c "/opt/spark/sbin/start-worker.sh  spark://spark-master:7077; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events
    
  spark-history-server:
    image: spark
    build: .
    container_name: spark-history-server
    entrypoint: "/bin/sh"
    command: -c "/opt/spark/sbin/start-history-server.sh; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events 
    ports:
      - '18080:18080'

  postgres:
    image: postgres:13
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8050:80"

volumes:
  spark-events:
